# Generated by Django 6.0.2 on 2026-02-27 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receipt_url',
        ),
    ]
