# Generated by Django 6.0.2 on 2026-02-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expense_receipt_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
